version=0.1
[default.global.parameters]
stack_name = "sam-layers"
 
[default.deploy.parameters]
region = "us-west-2"
s3_bucket = "REPLACE_BUCKET_NAME"
s3_prefix = "layers"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
tags = "project=\"ca-labs\" stage=\"development\""