AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  # DynamoDB Table
  LabTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  # Lambda Function
  NodejsLabFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: NodejsLabFunction
      CodeUri: src/
      Handler: putItem.handler
      Runtime: nodejs16.x
      Role: REPLACE_ROLE_ARN
      Environment:
        Variables:
          TableName: !Ref LabTable

  # Lambda Layer

Outputs:
  TableName:
    Value: !Ref LabTable
