AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
  PutItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: putItem.handler
      Runtime: nodejs16.x
      Role: REPLACE_ROLE_ARN
      Environment:
        Variables:
          TableName: !Ref LabTable

  LabTable:
    Type: AWS::Serverless::SimpleTable